### ISSUE TITLE
Data Folder

### ISSUE THREAD

**Issue by Yanay1** [clinicalml/sc-foundation-eval#1]
Hello! Nice preprint :)

Is the data directory available to download? Eg the raw h5ads for each dataset.

Thanks!

**Comment by rboiarsky** [comment]
Hi, and thanks for your interest! 

The myeloid, multiple sclerosis, and pancreas datasets were downloaded from the scGPT repo: https://github.com/bowang-lab/scGPT/tree/main/data#datasets-for-cell-type-annotation. I'll update the documentation to make this explicit.

I'll upload an easily accessibly h5ad for the Zheng68K PBMC data to our repo and will update this thread once it's there.

**Comment by Yanay1** [comment]
Thank you!

**Comment by rboiarsky** [comment]
updated! https://github.com/clinicalml/sc-foundation-eval/tree/main#data-availability
