### ISSUE TITLE
gene2vec data

### ISSUE THREAD

**Issue by sahil-sahni** [clinicalml/sc-foundation-eval#7]
Is the gene2vec file "/data/rna_rep_learning/scBERT/gene2vec_16906.npy" available?
Thanks.

**Comment by rboiarsky** [comment]
Hi, and thanks for your interest! Unfortunately the file is too large for me to upload to GitHub (27 MB). I got the file from the scBERT authors, you can email them at [fionafyang@tencent.com](mailto:fionafyang@tencent.com) to ask for it (see e.g. [this issue](https://github.com/TencentAILabHealthcare/scBERT/issues/47) where someone else asked them for it). Best of luck!
